### ISSUE TITLE
import from server fails

### ISSUE THREAD

**Issue by evoludolab** [LycheeOrg/Lychee#867] opened 2021-01-14 20:39 UTC
### Detailed description of the problem
Import from server of folder hierarchy fails (at least after refactoring in 1ce756e). Photos in the top level directory are imported as expected but the import of subdirectories fails with ``Server error or API not found.`` More precisely, with ``SyntaxError: JSON Parse error: Unterminated string`` (from the browser console).

In case it matters, in my setup I have ``import_via_symlink`` enabled and the subdirectories I am trying to import include space characters.

### Output of the diagnostics
```
Lychee Version (git):            master (1ce756e) - Data not in Cache
DB Version:                      4.2.0

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Darwin
PHP Version:                     7.4
Max uploaded file size:          200M
Max post size:                   100M
SQLite Version:                  3.34.0

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1691
GD Version:                      bundled (2.1.0 compatible)

Config Information
------------------
version:                         040200
check_for_updates:               0
sorting_Photos_col:              title
sorting_Photos_order:            ASC
sorting_Albums_col:              title
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay:                   1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:          
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    1
share_button_visible:            0
import_via_symlink:              1
has_ffmpeg:                      1
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
```

### Browser and system
macOS 10.15.7, Safari 14.0.2

**Comment by kamil4** [comment] 2021-01-14 21:01
Confirmed. The issue is with creating a subfolder; we are invoking the `create` method on a wrong class. Sorry, this is obviously a case we haven't tested before the refactoring got merged.

**Closed as completed** 2021-01-14 22:43 UTC
Labels: High Priority

**Comment by kamil4** [comment] 2021-01-14 22:45
OK, should be fixed. I encountered two more bugs while working on this one, one of which still remains to be fixed...

Thanks for the report!

**Comment by whcrg** [comment] 2022-02-25 09:49
For me server import fails with first photo imported. No error message seen other than "failed"
<img width="531" alt="image" src="https://user-images.githubusercontent.com/46355292/155693432-80ba6408-e6fd-490b-a1a9-91d1b6c3dd5f.png">

apache error.log has nothing that would make sense to me. 
`[Fri Feb 25 11:36:44.649675 2022] [proxy_fcgi:debug] [pid 1005] mod_proxy_fcgi.c(1021): [client 192.168.1.4:49388] AH01076: url: fcgi://localhost/storage/www/html/lychee/index.php proxyname: (null) proxyport: 0
[Fri Feb 25 11:36:44.650992 2022] [proxy_fcgi:debug] [pid 1005] mod_proxy_fcgi.c(1028): [client 192.168.1.4:49388] AH01078: serving URL fcgi://localhost/storage/www/html/lychee/index.php
[Fri Feb 25 11:36:44.652966 2022] [proxy:debug] [pid 1005] proxy_util.c(2332): AH00942: FCGI: has acquired connection for (*)
[Fri Feb 25 11:36:44.655320 2022] [proxy:debug] [pid 1005] proxy_util.c(2385): [client 192.168.1.4:49388] AH00944: connecting fcgi://localhost/storage/www/html/lychee/index.php to localhost:8000
[Fri Feb 25 11:36:44.656650 2022] [proxy:debug] [pid 1005] proxy_util.c(2422): [client 192.168.1.4:49388] AH02545: fcgi: has determined UDS as /run/php/php8.0-fpm.sock
[Fri Feb 25 11:36:44.660746 2022] [proxy:debug] [pid 1005] proxy_util.c(2594): [client 192.168.1.4:49388] AH00947: connected /storage/www/html/lychee/index.php to httpd-UDS:0
[Fri Feb 25 11:36:44.663852 2022] [proxy:debug] [pid 1005] proxy_util.c(2965): AH02823: FCGI: connection established with Unix domain socket /run/php/php8.0-fpm.sock (*)
[Fri Feb 25 11:36:45.869034 2022] [proxy:debug] [pid 1005] proxy_util.c(2347): AH00943: FCGI: has released connection for (*)`

Possibly related? Known issue? How to debug further?

Version: whatever git clone gave me today morning.

**Comment by ildyria** [comment] 2022-02-25 09:51
You did no show any of the debugging pages.
Nor anything in the lychee log page...

**Comment by whcrg** [comment] 2022-02-25 09:54
How do I access debugging page? I have debugging turned on in the .env a far as I know.

**Comment by ildyria** [comment] 2022-02-25 09:55
https://lycheeorg.github.io/docs/faq.html#lychee-is-not-working

**Comment by whcrg** [comment] 2022-02-25 10:43
Imagic seemed to be missing, but adding that (and restarting apache) actually didn't seem to help much. Now it chokes after 2-3 photos.

The diagnostics page seems not to be updating (changing max upload size etc do not showing). Should Lychee be reconfigured after such?

**Comment by ildyria** [comment] 2022-02-25 10:51
max upload size etc might be defined in your `public/.htaccess`

**Comment by ildyria** [comment] 2022-02-25 10:51
> Now it chokes after 2-3 photos.

I call this progress.

**Comment by nagmat84** [comment] 2022-02-25 11:55
@whcrg Please post the diagnostic information of Lychee and Lychee's log.

The OP is 1 year ago and used a much older version of Lychee. The problem back then and your current problem might have totally unrelated reasons.

**Comment by whcrg** [comment] 2022-02-25 13:07
This was totally unrelated and not a problem in Lychee (though maybe setup instructions on memory and time allowances could warn about this?).

The problem was  php-fpm needed to be restarted separately from apache for changes as allowed run time and adding php-modules to take effect. Now the changes I have made to make this work actually took effect and it seems to be processing my test pics just fine (veeeeery slow as its ARM based NAS box with debian 10).

Anyone care to tell me where I should set timezone, its already set in system, .env and php.ini but still I get this nag "Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone"
