### ISSUE TITLE
Filesystem Requirements for Symlink Feature Should be Documented

### ISSUE THREAD

**Issue by linucksrox** [LycheeOrg/Lychee#1139] opened 2021-11-11 21:59 UTC
I opened this issue because I'm running a different server configuration, but this may be similar to #948 

### Detailed description of the problem [REQUIRED]
Running version 4.3.4 in Docker with a bind mounted director from the host to /pictures within the container. Importing anything from /pictures via the web UI as a symlink fails.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Run Lychee 4.3.4 via Docker, and bind mount a pictures directory from the host into /pictures in the container
2. Using the web UI, import from filesystem
3. Choose /pictures or some subfolder to import from
4. Click the Symbolic links option
5. Import

### Output of the diagnostics  [REQUIRED]
Check the logs and see output like this:
`2021-11-09 19:09:50 -- error   -- App\Actions\Import\Exec::do -- 256 -- Could not import file (/pictures/2011/11-November/IMAG0354.jpg)`

### Browser and system
Server: Linux/Docker - Lychee 4.3.4
Client: Brave 1.31.91, Windows 10

Questions from @kamil4:
> Do you get any messages when it fails?
- For every file in the directory, it says Skipped and "Could not import the file!" with the resulting log entry as described above.

> I'm assuming this was an import via the web UI -- have you tried via the command line (php artisan lychee:sync; if you are running 4.3.4, you will need to set the global config import_via_symlink; if you are running master, there's a commandline option now).
- I changed this setting from 0 to 1 and saved, but had the same results after trying again

> Is /pictures accessible to the user ID that your web browser is using?
So if you import from there not via symlink, it works?
- Yes, /pictures is readable and if I import without symlink, it works fine (but creates a duplicate which is what I'm trying to avoid)

**Comment by kamil4** [comment] 2021-11-17 05:08
Thank you and sorry for the delay in responding; I've been very busy in my daily life...

Anyway, I did look at your report and I continue to be baffled. This is the code that generates the log entry: https://github.com/LycheeOrg/Lychee/blob/8d41c0f928b3ffac8f07523a6b369f3daeee28df/app/Actions/Import/Exec.php#L254-L257

It is an exception handler so clearly an exception has occurred, but where from? Considering that it succeeds if importing via symlink is disabled, it would seem as if it has to be from here: https://github.com/LycheeOrg/Lychee/blob/8d41c0f928b3ffac8f07523a6b369f3daeee28df/app/Actions/Photo/Strategies/StrategyPhoto.php#L35-L49

It would seem that it must be `symlink` itself that fails but from the manual it doesn't seem that it generates exceptions... And an ordinary failure would result in an additional log entry in line 38...

Do any of the other devs have a suggestion what we should ask of @linucksrox to diagnose the problem?

**Comment by nagmat84** [comment] 2021-11-17 07:15
> It is an exception handler so clearly an exception has occurred, but where from?
>  [...]
> It would seem that it must be `symlink` itself that fails but from the manual it doesn't seem that it generates exceptions... 
> [...]
> Do any of the other devs have a suggestion what we should ask of @linucksrox to diagnose the problem?

Actually, `symlink` may throw exceptions as I  found out myself some time ago. The PHP documentation is very incomplete regarding exceptions especially wrt. to this low-level function. So I guess you are right.

Unfortunately, I have no time to reproduce this error using my own setup especially as I have not Docker at all. So I won't be able to run the debugger on it and extract the original exception.

Without knowing the original exception message it is really hard to tell what is going on (permission problem? lack of symlink support by filesystem? etc. pp.)

I already have another PR in the pipeline which will improve the whole exception handling and reporting. Especially there will be an option which enables to report the whole exception stack incl. the message of each exception along the stack to the front-end. Although this future PR won't fix this problem, this PR will help to diagnose issues like this much more easily.

Sorry I am not or a big help here. The only thing I can say is to be patient, wait until we habe better diagnostic procedures in place and don't use symlinks until then.

**Comment by kamil4** [comment] 2021-11-17 15:33
Thanks; that's still helpful as I naively trusted that the `symlink` manual page would be complete...

@linucksrox, I added some additional diagnostics that should help us diagnose why creating the symlinks fails. All you need to do is replace the file `Lychee/app/Actions/Import/Exec.php` in your installation with the content of 
https://raw.githubusercontent.com/LycheeOrg/Lychee/wip-symlink-except/app/Actions/Import/Exec.php . Repeat you import and check the logs again; they should contain a bit more information now on what's going on.

**Comment by linucksrox** [comment] 2021-11-17 15:41
@kamil4 thanks, I replaced Exec.php with the file you provided. I was too hasty in saying it wasn't working because I removed the file and tried replacing again, and this time it went back to failing on the symlink import.

The new log entry tells me:
`Could not import file (/pictures/src/IMG_20170705_163931.jpg): 0 symlink(): Operation not supported`

I wanted to see the full source and destination path that it was trying to link, so I added that to the log output and got this result:
`src path: /pictures/src/IMG_20170705_163931.jpg dst path: /var/www/html/Lychee/public/uploads/big/26b12673332659e8d77cd5b52670e43a.jpg`

It's trying to create the symlink in the /uploads directory which I have bind mounted into the docker container, but the host directory is actually a CIFS mount which I imagine explains why I'm not able to create symlinks in that location. I can confirm that I'm able to create symlinks in the /sym directory which is also bind mounted directly from the host as suggested in the documentation.

So I wonder why it's not attempting to create symlinks in the /sym directory and instead is using the /uploads directory.

Maybe there's another way I can approach this without having to use the import/upload functions? All I want to do is use Lychee to browse my existing gallery without duplicating the files, and I want to make sure the original files remain read only.

**Comment by nagmat84** [comment] 2021-11-17 18:01
> The new log entry tells me: `Could not import file (/pictures/src/IMG_20170705_163931.jpg): 0 symlink(): Operation not supported`

That is what I expected: The native low-level function `symlink` fails, because the filesystem does not support symbolic links.

> It's trying to create the symlink in the /uploads directory which I have bind mounted into the docker container, but the host directory is actually a CIFS mount.

And that explains why. CIFS does not support symlinks. You need to use another filesystem which does.

> So I wonder why it's not attempting to create symlinks in the /sym directory and instead is using the /uploads directory.

The symbolic links are created below the `/uploads` directory, because this is the folder where the media files reside. Either the media files are copied into this directory (if truly imported without symbolic links) or symbolic links are created when import with symbolic links is activated.

The directory `sym` serves a completely different purpose. This directory is used to create short-living, temporary symbolic links when an image is served to the front-end. These symbolic links are meant as a security enhancing mechanism so that an attacker cannot (easiliy) guess the download path of an media file and thus circumvent access control. 

> Maybe there's another way I can approach this without having to use the import/upload functions? All I want to do is use Lychee to browse my existing gallery without duplicating the files, and I want to make sure the original files remain read only.

This heavily depends on the structure of your file system. At least the file system on which `/uploads` resides must support symbolic links (e.g. ext3/4, btrfs, zfs, etc.). "Windows" file system (e.g. ntfs, fat, cifs) won't work. The directory with the original media files may still be a windows file system. This is, because symbolic links (as opposed to hard links) may cross file system boundaries.

**Comment by linucksrox** [comment] 2021-11-17 18:42
Thank you very much for helping me understand why this doesn't work in my scenario! I will try another approach so that I'm using the native filesystem and not mounting via CIFS.

**Comment by ildyria** [comment] 2021-11-17 19:00
[This](https://github.com/LycheeOrg/Lychee/issues/1139#issuecomment-971824496) should be added in the FAQ: https://lycheeorg.github.io/docs/faq.html

**Closed as completed** 2022-07-16 09:39 UTC
Labels: Not an Issue/Wont fix, Documentation
