### ISSUE TITLE
[Enhancement] Watermarks

### ISSUE THREAD

**Issue by andjar** [LycheeOrg/Lychee#1063] opened 2021-07-15 18:47 UTC
In some cases it is useful to add watermarks to images at upload. Preferably, one should be able to choose which images that should be watermarked (say: only the original quality; or only the public version of the image)

One simple implementation is by adding a semitransparent box with your name in the middle of the image (inspired by https://programmerblog.net/watermark-images-using-php/):

```php
    public function watermark(
        string $source,
        string $destination
    ): bool {
        
        $res = $this->readImage($source);
        if ($res === false) {
            return false;
        }
        list($sourceImg, $mime, $width, $height) = $res;

        $stamp = imagecreatetruecolor(200, 70);
        imagefilledrectangle($stamp, 0, 0, 199, 169, 0x0000FF);
        imagefilledrectangle($stamp, 9, 9, 190, 60, 0xFFFFFF);
        imagestring($stamp, 5, 20, 20, 'My Name', 0x0000FF);
        imagestring($stamp, 3, 20, 40, '(c) 2021', 0x0000FF);

        $right = $width/2;
        $bottom = $height/2;
        $sx = imagesx($stamp);
        $sy = imagesy($stamp);

        imagecopymerge($sourceImg, $stamp, imagesx($sourceImg) - $sx - $right, imagesy($sourceImg) - $sy - $bottom, 0, 0, imagesx($stamp), imagesy($stamp), 50);

        if ($this->writeImage($destination, $sourceImg, $mime) === false) {
            return false;
        }

        imagedestroy($sourceImg);
        imagedestroy($stamp);

        return true;
    }
```

I added that code to `/public_html/Lychee/app/Image/GdHandler.php`, and a dummy for imagick:

```php
    public function watermark(
        string $source,
        string $destination
    ): bool {
        return true;
    }
```

And then called

```php
$filename = $photo->url;
        $url = Storage::path('big/' . $filename);
        if (!$this->imageHandler->watermark($url, $url)) {
            Logs::error(__METHOD__, __LINE__, 'Failed to watermark image');

            return false;
        }
```

in `/public_html/Lychee/app/Actions/Photo/Extensions/ImageEditing.php`.

**Comment by d7415** [comment] 2021-07-15 21:47
Duplicate of #743.

**Closed as completed by d7415** 2021-07-15 21:47 UTC
