### ISSUE TITLE
Image title and date overlay causes flicker

### ISSUE THREAD

**Issue by eip618** [LycheeOrg/Lychee#916] opened 2021-02-12 09:58 UTC
### Detailed description of the problem [REQUIRED]
Hovering over some images produces a flickering effect.
I believe the offending CSS to be
```*{-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;-webkit-transition:color .3s,opacity .3s ease-out,-webkit-transform .3s ease-out,-webkit-box-shadow .3s;transition:color .3s,opacity .3s ease-out,transform .3s ease-out,box-shadow .3s,-webkit-transform .3s ease-out,-webkit-box-shadow .3s;-o-transition:color .3s,opacity .3s ease-out,transform .3s ease-out,box-shadow .3s}```

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
Seems to only happen on certain images. I am unsure if this is to do with format, size, etc...

**Screenshots**
Will get a video shortly

### Output of the diagnostics  [REQUIRED]
`    Warning: Dropbox import not working. dropbox_key is empty.`

### Browser and system
Chrome, Win10

**Comment by ildyria** [comment] 2021-02-12 10:06
I noticed that too recently.
I do not know what **changed** in the front end that is now doing this.

**Comment by kamil4** [comment] 2021-02-12 15:33
Weird; I haven't noticed anything like that. Could it be browser-dependent? I normally use Firefox, although I just tried with Chrome and I don't see any flicker either...

**Comment by ildyria** [comment] 2021-02-12 15:54
> I noticed that too recently.
> I do not know what **changed** in the front end that is now doing this.

Okay, I don't have the bug anymore on my Linux + Chrome.

**Comment by kamil4** [comment] 2021-02-12 18:43
@eip618 Sounds like we'll need a video from you then since we can't reliably reproduce it. And a complete Diagnostics output, with all the settings. If it's a public gallery, it would really help to have the URL that we could try out to see the problem on our end.

**Comment by ildyria** [comment] 2021-02-15 13:20
> Chrome, Win10

I confirm the bug on that specific configuration which leads me to think this is a specific bug related to Chrome.

**Comment by ildyria** [comment] 2021-02-15 13:24
https://stackoverflow.com/questions/10134935/weird-css3-transition-flickering
https://www.xspdf.com/resolution/10529134.html
https://stackoverflow.com/questions/3790273/webkit-support-for-gradient-transitions

**Comment by eip618** [comment] 2021-02-16 01:01
> @eip618 Sounds like we'll need a video from you then since we can't reliably reproduce it. And a complete Diagnostics output, with all the settings. If it's a public gallery, it would really help to have the URL that we could try out to see the problem on our end.

i've removed the offending css from my installation at the present time, i can add it back later. for the moment the overlay just pops in and pops out. the install is located at https://album.eiphax.tech

what is the best way to provide diagnostics output?

**Comment by d7415** [comment] 2021-02-17 13:22
> what is the best way to provide diagnostics output?

From the issue template:

> *(Settings => Diagnostics or https://example.com/Diagnostics or php artisan lychee:diagnostics)*

**Comment by eip618** [comment] 2021-03-01 02:02
> From the issue template:
> 
> > _(Settings => Diagnostics or https://example.com/Diagnostics or php artisan lychee:diagnostics)_

Yes, that much I get, I mean do you want it as a text document? Copy pasted here? Blockquoted with markdown?

**Comment by ildyria** [comment] 2023-09-02 20:27
I guess this is resolved with newer browser versions.

**Closed as completed by ildyria** 2023-09-02 20:27 UTC
Labels: upstream
