### ISSUE TITLE
[Enhancement]Markdown link

### ISSUE THREAD

**Issue by scmaybee** [LycheeOrg/Lychee#608] opened 2020-06-02 11:10 UTC
*Target*
Use Lychee as a images base.

*Copy markdown link*
Upload to a specified album, and could easy copy the link to insert a markdown document.
If it could make 'keep the original filename' as an option is OK.

Something like 
`![***.jpg](http://0.0.0.0:0000/images/***.jpg)`

*Better*
Typora support use a custom command to auto upload images in markdown, if Lychee could response the link to it will be better.

**Comment by d7415** [comment] 2020-06-02 11:23
Image URLs can be accessed from the share menu. I don't see an advantage to supporting markdown specifically, and it would probably clutter the interface.

Second part is a duplicate of #526.

I'm going to close this. If someone else from the project is interested they can reopen.

**Closed as completed** 2020-06-02 11:24 UTC
