### ISSUE TITLE
Instalation loop & DB crash & mobile version error & no settings

### ISSUE THREAD

**Issue by michelangelo136** [LycheeOrg/Lychee#818] opened 2020-12-15 16:41 UTC
### Detailed description of the problem [REQUIRED]
I have installed Lychee on a dedicated ubuntu 20.04 server, I'm runing it using apache2, and mariadb, but every time i try to login it crashes the mariadb and throws me to the installation screen, when I restart the mariadb service I'm able to login normally, after the login I can upload photos, but I can't change the settings, when i press the button it loads for half a second and then it throws me to the main page, when i try to login from my phone, i get the error "Session timed out", i tried logging in from inprivate windows and different devices but the problems persists, the diagnostics page is clear except the  
dropbox_key which is irrelevant.

### Steps to reproduce the issue

1. Manually install Lychee on ubuntu 20.04.
2. Use mariadb and apache2.
3. Complete installation with manuall creation of DB.
4. Create account.
5. Try to open the settings menu RESULT -> menu opens for a split second and then you are returned to the home page.
6. Try to refresh the page after some minutes of inactivity RESULT -> the mariadb.service has crashed with error code "timeout".
7. Restart mariadb.service and try to login from a mobile device RESULT -> Get "error: Session timed out."
8. Try to login from Desktop, click the install button RESULT -> steps from 2-4 are skipped and now you are logged in.
9. Repeat steps 5 through 8 and you will have the same "result", thus we have a loop 

### Output of the diagnostics
 Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee Version (git):            master (9b477f7) - Up to date (8 minutes ago).
    DB Version:                      4.0.8
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    MySQL Version:                   10.3.25-MariaDB-0ubuntu0.20.04.1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5

    Config Information
    ------------------
    version:                         040008
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0

### .env config

APP_NAME="Lychee - Vault"
APP_ENV=production
APP_KEY=base64:REDACTED
APP_DEBUG=false
APP_URL=http://vault.local
DEBUGBAR_ENABLED=false
LOG_CHANNEL=stack
DB_OLD_LYCHEE_PREFIX=

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306 
DB_DATABASE=lychee
DB_USERNAME=REDACTED
DB_PASSWORD=REDACTED
DB_LOG_SQL=false

TIMEZONE=EET
BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync
SECURITY_HEADER_HSTS_ENABLE=false
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
MAIL_DRIVER=
MAIL_HOST=
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1
MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

### Browser and system
Server:
Ubuntu 20.04

Client 1:
Ubuntu 20.04, Firefox

Client 2:
Manjaro Architect, Firefox

Client 3:
Android 10, Firefox (yeah, I like firefox)

Any idea is more than welcome.

**Comment by ildyria** [comment] 2020-12-15 17:09
That is very surprising. Especially given that the install process is actually checked in one of our test.

I'll try to have a look when I have time :( sorry.

**Comment by michelangelo136** [comment] 2020-12-15 21:01
@ildyria Thanks :)

**Comment by ildyria** [comment] 2020-12-21 10:14
Sorry for the delay, and I could not reproduce. :(

Can you try to update your MariaDB version ? I'm using `10.5.8-MariaDB-3`.

PS: thank you for using the latest version (master) by the way. This helps. :+1:

**Closed as completed** 2021-01-09 17:27 UTC
Labels: More info required
