### ISSUE TITLE
Square thumbnails are not being rotated

### ISSUE THREAD

**Issue by DMXMax** [LycheeOrg/Lychee#853] opened 2021-01-04 23:49 UTC
Using lychee 4.1.0 in a container (lycheeorg/lychee:latest)

steps to reproduce:
1. Under settings set the photo layout to 'square thumbnails'
2. Import photo from the server where the orientation is wrong
3. Browse album and photo. Note the thumbnail and the original has the original (wrong) orientation
4. Rotate the photo
5. Note the thumbnail and original (if refreshed) are orientated correctly
6. Refresh the album: Note the thumbnail orientation 'reverts' to original orientation while the 'original' photo now has the correct orientation

**Comment by ildyria** [comment] 2021-01-04 23:59
Refresh the cache with CTRL+F5 ?

**Comment by kamil4** [comment] 2021-01-05 00:01
Duplicate of #741.

**Closed as completed by kamil4** 2021-01-05 00:01 UTC

**Comment by DMXMax** [comment] 2021-01-12 04:27
> Refresh the cache with CTRL+F5 ?

Not quite. I did try that. *But* thanks for turning me on to the idea of clearing out my browsing data (cache). Doing it that way fixes it, but Ctrl-F5 for some reason does not.

**Comment by kamil4** [comment] 2021-01-12 05:22
I promise to make fixing this my priority as soon as the massive #832 refactoring PR is merged.

**Comment by DMXMax** [comment] 2021-01-12 14:35
No problem. The work around works great and kudos to all the great work you're doing on this product.
