### ISSUE TITLE
Albums or photos are incorrectly set after migration from Lychee v3.x

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#927] opened 2021-02-15 10:37 UTC
### Detailed description of the problem [REQUIRED]
I have some albums set to be: public, hidden, and protected with pass (with Lychee v3).
But it does not work properly, without changes.

If I click "unpublish" and "publish" again, it works as expected with certain settings.
But without it, v3 settings for albums does not work.
The first effect, after loading certaing public hidden album v3 is that there is no pass popup, just all images are shown.

Next time, I tried to disable "original images" or set password (pass was set in v3 version, here there was no indication of that setting - just like the pass was not set), images disappeared completely.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to album that was set with settings, ex. pass, public, hidden etc.. in v3 version of Lychee
2. Do nothing - just copy the URL
3. Go to ex. incognito window
4. Load URL - see what happens..

**Screenshots**
database - sample album, set with Lychee v3, I did not changed anything here:
![firefox_GWfTya4wtr](https://user-images.githubusercontent.com/25976749/107935416-a7b42f00-6f81-11eb-8187-ee3c9785be1c.png)
![firefox_4Y78PHhvUV](https://user-images.githubusercontent.com/25976749/107935420-a8e55c00-6f81-11eb-92b3-d80250257076.png)

photos from this album:
![firefox_H7nP3AEEXv](https://user-images.githubusercontent.com/25976749/107935450-b3075a80-6f81-11eb-9ecb-c28ee2e39d02.png)
![firefox_JpCIiAA6re](https://user-images.githubusercontent.com/25976749/107935452-b39ff100-6f81-11eb-9606-d6cdb0978cf5.png)
![firefox_ADnPk0fFnZ](https://user-images.githubusercontent.com/25976749/107935453-b4388780-6f81-11eb-93ed-723e146e54cc.png)

### Output of the diagnostics  [REQUIRED]
Not required I think.

### Browser and system
**OS:** Win7 PRO
**Browser:** Firefox 85.0.2 (64 bity)

**Comment by kamil4** [comment] 2021-02-16 19:47
Looking at the source code: https://github.com/LycheeOrg/Lychee/blob/3274d9aef5ef00126d8006b9161c10538c5b130f/database/migrations/2018_08_15_102039_move_albums.php#L25-L33
I can confirm that passwords aren't being copied between the v3 and v4 albums. I'm not sure why -- perhaps the password encoding schemes are incompatible between the two? @ildyria?

**Comment by kamil4** [comment] 2021-02-16 19:55
It looks like they both use bcrypt...

**Comment by kamil4** [comment] 2021-02-16 21:55
OK, this will get fixed, but it won't affect you since your albums have already been migrated. What I mean by that is that you would have to start from v3 again to benefit from the fix.

**Comment by elvisef** [comment] 2021-04-29 06:35
Alright, I understand. I will need to do it manually : )
I hope the "save" button will work out of the box.

**Edit:** Just saving using a button did not help. It did not, because the "secured" option is disabled when entering album options (v3 migrated and secured with password album). So I need to enter a new password and then save.
![firefox_2021-04-29_08-42-45](https://user-images.githubusercontent.com/25976749/116511400-acbd2500-a8c6-11eb-9a58-1b37a5062a43.png)

**Comment by ildyria** [comment] 2021-04-29 09:24
It seems we need to copy an additional data :(

**Comment by kamil4** [comment] 2021-04-29 14:04
I'm not sure what the issue is?

We are talking about albums that were migrated from v3 _before_ #928 was merged, correct? In that case the passwords weren't copied, so indeed in order to re-enable the passwords one needs to check the _Password protected_ box and then enter the password in the input field that appears. This is how it's supposed to work.

**Comment by elvisef** [comment] 2021-04-30 09:18
Yes. I just wrote it in order to remember to let know other users in the FAQ or wherever, if they have problems as in my case.
I have nothing else to say here though : )

**Closed as completed** 2021-04-30 14:04 UTC
