### ISSUE TITLE
Check for updates on UI throws error

### ISSUE THREAD

**Issue by tmp-hallenser** [LycheeOrg/Lychee#755] opened 2020-10-11 10:21 UTC
### Detailed description of the problem [REQUIRED]
* "Check for updates" fails

### Steps to reproduce the issue
* Run latest docker version (v4.0.7)
* Click on "Check for updates" under Diagnostics 
* "Error: count(): Parameter must be an array or object that implements Countable"  
* Without debugging, I'd guess it's this line: https://github.com/LycheeOrg/Lychee/blob/dd979aba0e382aea04d549a403c1d4f6caa0fc69/app/Metadata/GitHubFunctions.php#L144

### Output of the diagnostics  [REQUIRED]
```



Diagnostics
-----------
Info: Latest version of PHP is 7.4
Warning: Using 32 bit PHP, recommended upgrade to 64 bit
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Dropbox import not working. dropbox_key is empty.

System Information
------------------
Lychee Version (git):            master (a50112c) - Data not in Cache
DB Version:                      4.0.7

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.3
Max uploaded file size:          2M
Max post size:                   8M
MySQL Version:                   10.1.44-MariaDB-0ubuntu0.18.04.1

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1690
GD Version:                      2.2.5

Config Information
------------------
version:                         040007
check_for_updates:               0
sorting_Photos_col:              takestamp
sorting_Photos_order:            ASC
sorting_Albums_col:              max_takestamp
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay:                   1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:          
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     1
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    1
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      1
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov

```

### Browser and system
Docker on armv7, Safari

**Comment by ildyria** [comment] 2020-10-15 10:17
I cannot reproduce. That is weird.

**Comment by ildyria** [comment] 2020-10-15 10:59
@d7415 can you check that one ?

**Comment by d7415** [comment] 2020-10-16 15:46
My gut feeling was a problem with the git checks or my workarounds, but I can't even make the button appear in `:v4.0.7` or `:dev`. I have mixed feelings about whether that's the desired behaviour, but it's probably standard.

**Comment by tmp-hallenser** [comment] 2020-10-16 15:59
Do you have git installed on the container? I think I added it some time
ago.

Am Fr., 16. Okt. 2020 um 17:46 Uhr schrieb Martin Stone <
notifications@github.com>:

**Comment by d7415** [comment] 2020-10-16 21:52
> Do you have git installed on the container?

Nope

**Comment by d7415** [comment] 2020-10-27 20:08
Installed git. Still no button...

**Comment by ildyria** [comment] 2020-11-21 18:31
Humm... possible explanation is the https again (similar bug for the map queries).

**Comment by ildyria** [comment] 2020-12-27 15:06
I think this is fixed with the latest update of https://github.com/LycheeOrg/Lychee-docker

**Closed as completed** 2021-01-09 17:26 UTC
Labels: More info required
