### ISSUE TITLE
Adding .mp4 to an album makes images disappear

### ISSUE THREAD

**Issue by ezek1el** [LycheeOrg/Lychee#1014] opened 2021-05-22 08:00 UTC
### Detailed description of the problem
Adding .mp4 files to an album leads to empty album. 

### Steps to reproduce the issue

1. create new folder
2. add image
3. add .mp4
4. folder goes blank

### Output of the diagnostics
```
    2021-05-22 07:56:37 -- notice  -- App\Actions\Photo\Extensions\VideoEditing::extractVideoFrame -- 29 -- Failed to extract snapshot: bad config: 
    2021-05-22 07:56:37 -- notice  -- App\Metadata\Extractor::extract -- 112 -- FFmpeg and Exiftool not being available; Extraction of metadata limited to mime type and file size.
    2021-05-22 07:56:09 -- notice  -- App\Image\ImagickHandler::scale -- 113 -- Saving thumb to /***/Lychee/public/uploads/small/123123123123.jpg
    2021-05-22 07:56:08 -- notice  -- App\Image\ImagickHandler::scale -- 113 -- Saving thumb to /***/Lychee/public/uploads/small/1231231231239.jpg
    2021-05-22 07:56:08 -- notice  -- App\Image\ImagickHandler::scale -- 113 -- Saving thumb to /***/Lychee/public/uploads/medium/123123123123.jpg
    2021-05-22 07:56:08 -- notice  -- App\Image\ImagickHandler::scale -- 113 -- Saving thumb to /***/Lychee/public/uploads/medium/3123123123.jpg
    2021-05-22 07:56:07 -- notice  -- App\Image\ImagickHandler::crop -- 161 -- Saving thumb to /***/Lychee/public/uploads/thumb/123123123.jpeg
    2021-05-22 07:56:07 -- notice  -- App\Image\ImagickHandler::crop -- 161 -- Saving thumb to /***/Lychee/public/uploads/thumb/2123123123.jpeg
    2021-05-22 07:56:06 -- notice  -- App\Actions\Photo\Extensions\ImageEditing::createThumb -- 165 -- Photo URL is 123123123231.jpg
    2021-05-22 07:27:24 -- error   -- App\Metadata\Extractor::extract -- 120 -- Given path () to the ffprobe binary is invalid
    2021-05-22 07:27:24 -- error   -- App\Metadata\Extractor::extract -- 120 -- Given path () to the ffprobe binary is invalid
    2021-05-22 07:24:33 -- error   -- App\Metadata\Extractor::extract -- 120 -- Given path () to the exiftool binary is invalid
    2021-05-22 07:24:05 -- error   -- App\Metadata\Extractor::extract -- 120 -- Given path () to the exiftool binary is invalid
    2021-05-22 07:23:49 -- error   -- App\Metadata\Extractor::extract -- 120 -- Given path () to the exiftool binary is invalid
    2021-05-22 07:22:16 -- error   -- App\Metadata\Extractor::extract -- 120 -- Given path () to the ffprobe binary is invalid
    2021-05-22 07:22:16 -- error   -- App\Metadata\Extractor::extract -- 120 -- Given path () to the ffprobe binary is invalid
    2021-05-22 07:22:05 -- error   -- logResult -- 103 -- Process errored with `sh: jpegoptim: command not found   
```

### Browser and system
Firefox 88.0.1, MS Edge 90.0.818.62, Win 10 x64

**Comment by kamil4** [comment] 2021-05-23 15:26
Which version of Lychee are you on? It would be best if you included the full diagnostics. Thanks!

**Comment by ezek1el** [comment] 2021-05-23 15:32
```
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8

    System Information
    --------------
    Lychee Version (git):            master (85dfc64) - Data not in Cache
    DB Version:                      4.3.2
    
    composer install:                dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    SQLite Version:                  3.26.0
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1802
    GD Version:                      2.2.5

    
    Lychee total space:              2.63 GB
    Upload folder space:             2.53 GB
    System total space:              2.08 TB
    System free space:               246.36 GB (11%)

    Config Information
    --------------
    version:                         040302
    check_for_updates:               1
    sorting_Photos_col:              title
    sorting_Photos_order:            ASC
    sorting_Albums_col:              title
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 1
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1280
    medium_max_height:               720
    lang:                            de
    layout:                          2
    image_overlay_type:              desc
    default_license:                 CC-BY-NC-ND-4.0
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 1
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   name
    landing_title:                   name
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      name
    site_copyright_enable:           1
    site_copyright_begin:            2015
    site_copyright_end:              2021
    additional_footer_text:          this text should be funny, but it is not.
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   0
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov|.mp4
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            0
```

**Comment by kamil4** [comment] 2021-05-25 03:31
Confirmed. Looks like a front-end issue...

**Comment by kamil4** [comment] 2021-05-25 05:16
Fix pending review.

**Comment by kamil4** [comment] 2021-05-25 22:17
This should now be on the master branch as of 75c78e5fc1ac6640591d6bedba73f5bd602e0037. Can you test and close this issue if it's fixed? Thanks!

**Comment by ezek1el** [comment] 2021-05-29 21:31
tested. It's fixed. Thank you!  💙

**Closed as completed** 2021-05-29 21:31 UTC
Labels: High Priority
