### ISSUE TITLE
videos uploaded before ffmpeg/ffprobe don't geenrate thumbnails

### ISSUE THREAD

**Issue by eip618** [LycheeOrg/Lychee#1182] opened 2021-12-30 15:18 UTC
### Detailed description of the problem [REQUIRED]
videos do not show thumbnails if ffmpeg and ffprobe were installed *after* the relevant videos were uploaded

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. upload some videos without ffmpeg and ffprobe installed
2. install ffmpeg and ffprobe
3. upload new videos
4. new videos have thumbnails, old ones do not

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (release):        4.4.0
    DB Version:                      4.4.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8.1
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          2G
    Max post size:                   2G
    Max execution time:              200
    MySQL Version:                   8.0.27-0ubuntu0.20.04.1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.3.0

### Browser and system
chrome, windows 10

**Comment by kamil4** [comment] 2021-12-30 15:38
Yes, this is the expected behavior. We generate thumbnails once during import/upload, not on every access.

If you have commandline access to your server though, we do provide a way to regenerate them later. Simply invoke the following while in your top-level Lychee directory:
```
php artisan lychee:video_data
```

Otherwise, you'll need to reupload the videos...

**Comment by LouisVallat** [comment] 2021-12-30 18:12
As it seems to be the expected behavior, I'm closing this issue.

**Closed as completed by LouisVallat** 2021-12-30 18:12 UTC
Labels: Not an Issue/Wont fix
