### ISSUE TITLE
The demo on the website is still at 3.2.8

### ISSUE THREAD

**Issue by thansk** [LycheeOrg/Lychee#855] opened 2021-01-08 15:49 UTC
### Detailed description of the problem [REQUIRED]
The demo on the website (https://lycheeorg.github.io/demo/) is still at version 3.2.8 while the latest one is 4.1.0 and does not paint the project in its best light when a new user tests it out.

### Output of the diagnostics  [REQUIRED]
N/A

**Comment by d7415** [comment] 2021-01-08 15:55
Thanks, but duplicate of LycheeOrg/LycheeOrg.github.io#11 (I don't really expect you to look there though :) )

**Closed as completed by d7415** 2021-01-08 15:55 UTC
