### ISSUE TITLE
Custom album covers

### ISSUE THREAD

**Issue by evoludolab** [LycheeOrg/Lychee#871] opened 2021-01-15 04:11 UTC
I would like to be able to select photos that are displayed as album covers. In particular, it would be nice to set the album cover by tagging one of its photos as the cover photo through the context menu. For albums that contain sub-albums, the sub-album-covers should also be available as potential covers for the parent album. This becomes particularly important if an album includes only sub-albums and no photos.

Maybe this could be implemented by leveraging the existing tags, e.g. by introducing an `AlbumCover`-tag. However, tagging multiple photos in one album could be an issue as well as if the tagged photo should serve as the cover of a parent album higher up in the hierarchy. Allowing users to override the default set by the owner of the album (if any) would be nice but certainly lower priority.

Since such an enhancement would possibly require changes to the backend and database structure, I post the feature request here rather than in Lychee-front.

Thanks for an impressive (and stunning) tool!

**Comment by d7415** [comment] 2021-01-15 10:45
Duplicate of #442. I've copied this contribution there. Thanks!

**Closed as completed by d7415** 2021-01-15 10:45 UTC
