### ISSUE TITLE
Animations makes me nervous : ) Something is still there...

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#911] opened 2021-02-09 16:38 UTC
### Detailed description of the problem [REQUIRED]
Why do the thumbnails are duplicated ? Or am I wrong ?
Look at my screenshots attached.

I have a feeling, that my album list is loading slower and slower.
How to disable any animations here ?

I will also attach a small video, to show weird things happening during animation.
**1st:** is when I go to the "slide menu", and when I hide it, the lag happens
**2nd:** is if I want to check "about" section, and know what the version is
**3rd:** also on the login screen (well known for me from the past (v3) version) while I go to mys domain, to login, the login "popup" shows itself for second and hides after a second under any of elements visible, or even showing itself but with lags a bit... this is very weird, maybe You know why it happens, and how to disable or fix it, hopefully..*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Just go to the album list
2. Inspect (chosen album) element
3. ..and see

**Screenshots**
![2021-02-09_17-26](https://user-images.githubusercontent.com/25976749/107394860-963fd280-6afc-11eb-8ca3-3fa818bb31c9.png)
![2021-02-09_17-27](https://user-images.githubusercontent.com/25976749/107394867-9770ff80-6afc-11eb-91d2-314445167eb2.png)

https://user-images.githubusercontent.com/25976749/107395773-680ec280-6afd-11eb-938f-e36a2640c27b.mp4

### Output of the diagnostics  [REQUIRED]
*Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

System Information
------------------
Lychee Version (git):            master (7e352be) - Data not in Cache
DB Version:                      4.2.1

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       true

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          20971520
Max post size:                   20971520
MySQL Version:                   5.7.33

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1687
GD Version:                      2.2.5

Config Information
------------------
version:                         040201
check_for_updates:               0
sorting_Photos_col:              id
sorting_Photos_order:            DESC
sorting_Albums_col:              id
sorting_Albums_order:            DESC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay:                   0
image_overlay_type:              exif
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 1
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:          
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle*

### Browser and system
OS: Debian 10.x
Browser: Firefox 78.x

**Comment by ildyria** [comment] 2021-02-09 17:18
> Why do the thumbnails are duplicated ? Or am I wrong ?

This is an optimization we made, and it significantly speed up on the back end.

> I have a feeling, that my album list is loading slower and slower.

The version 4 is actually bringing some speed optimizations, especially due to the subalbums.

> How to disable any animations here ?

You need to use the `user.css`. More here:
https://lycheeorg.github.io/docs/faq.html#how-to-disable-the-zoom-animation-while-browsing-pictures

You will probably need to also add more modifications, but this is the idea to allow any user to modify the layout as they see fit.

> **1st:** is when I go to the "slide menu", and when I hide it, the lag happens

The "lag" is a reload of the album pages. It could be optimized but that was already the case with version 3 when the left menu was implemented. If it was not in your experience, this means that you were not using the "latest" version of version 3.

Anyhow, I hope this will be improved in the new front-end version which is what I will be focusing on as a next project once I complete my official work...

> **2nd:** is if I want to check "about" section, and know what the version is

I never use the about section, always the Diagnostics. :sweat_smile: 
However I don't have the bug you are mentioning. Weird.

> **3rd:** also on the login screen (well known for me from the past (v3) version) while I go to mys domain, to login, the login "popup" shows itself for second and hides after a second under any of elements visible, or even showing itself but with lags a bit... this is very weird, maybe You know why it happens, and how to disable or fix it, hopefully..*

The login screen pops up immediately on my version. You can check here https://photography.viguier.nl 
If you press `L` it will pop up instantly, no double loading like in your case. The only possible culprit I could think of is that you have no pictures displayed. Even though, this should not be the case. A firefox bug maybe? :thinking:

**Comment by kamil4** [comment] 2021-02-09 17:57
> > Why do the thumbnails are duplicated ? Or am I wrong ?
> This is an optimization we made, and it significantly speed up on the back end.

Yeah, we used to display three separate thumb pictures, with one in the front and two behind. As the two behind were mostly obstructed, we got rid of them recently when adding the feature of being able to specify the cover thumb explicitly. But we didn't remove them completely since they provide a useful visual cue on which album a user is hovering over, so now we simply display the same thumb three times.

> > **1st:** is when I go to the "slide menu", and when I hide it, the lag happens
> 
> The "lag" is a reload of the album pages.

I don't think so. I don't see any network activity during that time so I don't think we are reloading them.

@elvisef, how many albums do you have at the top level? Judging by the size of the scrollbar in your video I would guess maybe around 300? That's a lot; I've never tested it with that many, but I know that Lychee slows down a lot when it needs to display a lot of images (try an album with over a thousand pictures and you'll see what I mean). So that would all be client-side slowdown, due to the overhead in your web browser of laying out all those images on the screen. Some of that could perhaps be optimized...

Keep in mind though that Lychee v4 supports subalbums, so instead of having this flat top level with hundreds of albums you could build yourself a nice hierarchy. That should speed things up considerably.

> > **2nd:** is if I want to check "about" section, and know what the version is
> 
> I never use the about section, always the Diagnostics. sweat_smile
> However I don't have the bug you are mentioning. Weird.

We are talking about that weird flicker, right? I can't reproduce it either. It pops up very smoothly for me (Firefox 84 under Linux).

> > **3rd:** also on the login screen (well known for me from the past (v3) version) while I go to mys domain, to login, the login "popup" shows itself for second and hides after a second under any of elements visible, or even showing itself but with lags a bit... this is very weird, maybe You know why it happens, and how to disable or fix it, hopefully..*

I'm not sure what behavior you are talking about. Is that shown in your video? I see a double loading that @ildyria mentioned but I assumed it was because you hit the reload in your browser?

**Comment by nagmat84** [comment] 2022-03-27 18:44
As the OP has never replied to the last post in two years, I close this issue. Moreover, with all the refactoring since then, the problem might even be outdated.

**Closed as completed by nagmat84** 2022-03-27 18:44 UTC
