### ISSUE TITLE
Multi select Delete album errors

### ISSUE THREAD

**Issue by sunosv** [LycheeOrg/Lychee#1330] opened 2022-05-15 09:00 UTC
### Detailed description of the problem

This problem is probabilistic

Because I only have a few albums for testing, I found that `_rgt` is not reset to 2 after deleting an album, that is, `_lft == 1` and  `_rgt == 2`. This causes a pending problem that will interfere the next time I delete multiple albums.

I tried php artisan lychee:fix-tree, but no help 

### Steps to reproduce the issue

1.Select multiple albums that has many sub-album and  Delete

[![未标题-1.png](https://sunos.top:1098/2022/05/15/354a70f7f8831.png)](https://sunos.top:1098/2022/05/15/354a70f7f8831.png)

before deletion
[![QQ截图20220515165255.png](https://sunos.top:1098/2022/05/15/84556c20d34a2.png)](https://sunos.top:1098/2022/05/15/84556c20d34a2.png)

after deletion
[![QQ截图20220515165533.png](https://sunos.top:1098/2022/05/15/79d32ad34bc0f.png)](https://sunos.top:1098/2022/05/15/79d32ad34bc0f.png)

### Show logs

```
2022-05-15 08:37:29 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 -- 
2022-05-15 08:37:29 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-15 08:35:22 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 -- 
2022-05-15 08:35:22 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-15 08:35:20 UTC -- error   -- PDOStatement::execute -- 526 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`))
2022-05-15 08:35:20 UTC -- error   -- App\Actions\Album\Delete::do -- 110 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)); caused by
2022-05-15 08:35:20 UTC -- error   -- Illuminate\Database\Connection::runQueryCallback -- 712 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)) (SQL: delete from `albums` where `albums`.`_lft` between 3 and 3 order by `_lft` desc); caused by
2022-05-15 08:35:20 UTC -- error   -- App\Actions\Album\Delete::do -- 110 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)) (SQL: delete from `albums` where `albums`.`_lft` between 3 and 3 order by `_lft` desc); caused by
2022-05-15 08:35:15 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 -- 
2022-05-15 08:35:15 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-15 08:35:11 UTC -- error   -- PDOStatement::execute -- 526 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`))
2022-05-15 08:35:11 UTC -- error   -- App\Actions\Album\Delete::do -- 115 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)); caused by
2022-05-15 08:35:11 UTC -- error   -- Illuminate\Database\Connection::runQueryCallback -- 712 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)) (SQL: delete from `albums` where `id` in (1nIuXcxoDaUSLyYka5-sM72D, aqeblDeFa2lwTL6dXWO3fVkK, qjiZ95tEPfybGnLoXAHvtmti, zFhv8f-2LBs-jkLXzaxh7TGi)); caused by
2022-05-15 08:35:11 UTC -- error   -- App\Actions\Album\Delete::do -- 115 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)) (SQL: delete from `albums` where `id` in (1nIuXcxoDaUSLyYka5-sM72D, aqeblDeFa2lwTL6dXWO3fVkK, qjiZ95tEPfybGnLoXAHvtmti, zFhv8f-2LBs-jkLXzaxh7TGi)); caused by
2022-05-15 08:21:51 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 -- 
2022-05-15 08:21:51 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-15 08:21:40 UTC -- error   -- PDOStatement::execute -- 526 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`))
2022-05-15 08:21:40 UTC -- error   -- App\Actions\Album\Delete::do -- 115 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)); caused by
2022-05-15 08:21:40 UTC -- error   -- Illuminate\Database\Connection::runQueryCallback -- 712 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)) (SQL: delete from `albums` where `id` in (7QCpaD04x1aLJoRkbaCjzVsJ, lQFYH0P0Cm6fnSr1vtf4IFmu, zna9BsMTKSd2k5SZfmELwXzs)); caused by
2022-05-15 08:21:40 UTC -- error   -- App\Actions\Album\Delete::do -- 115 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)) (SQL: delete from `albums` where `id` in (7QCpaD04x1aLJoRkbaCjzVsJ, lQFYH0P0Cm6fnSr1vtf4IFmu, zna9BsMTKSd2k5SZfmELwXzs)); caused by
2022-05-15 08:21:04 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 -- 
2022-05-15 08:21:04 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-15 08:20:42 UTC -- error   -- PDOStatement::execute -- 526 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`))
2022-05-15 08:20:42 UTC -- error   -- App\Actions\Album\Delete::do -- 115 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)); caused by
2022-05-15 08:20:42 UTC -- error   -- Illuminate\Database\Connection::runQueryCallback -- 712 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)) (SQL: delete from `albums` where `id` in (aFEBFXBIBIJFlxS4LFyRp6bx, aFEBFXBIBoKAthE6nqRKC9Iz, aFEBFXBIBoyXOBE9jFbMn6mU)); caused by
2022-05-15 08:20:42 UTC -- error   -- App\Actions\Album\Delete::do -- 115 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)) (SQL: delete from `albums` where `id` in (aFEBFXBIBIJFlxS4LFyRp6bx, aFEBFXBIBoKAthE6nqRKC9Iz, aFEBFXBIBoyXOBE9jFbMn6mU)); caused by
2022-05-15 08:20:38 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 -- 
2022-05-15 08:20:38 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-15 08:19:46 UTC -- error   -- PDOStatement::execute -- 526 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`))
2022-05-15 08:19:46 UTC -- error   -- App\Actions\Album\Delete::do -- 115 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)); caused by
2022-05-15 08:19:46 UTC -- error   -- Illuminate\Database\Connection::runQueryCallback -- 712 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)) (SQL: delete from `albums` where `id` in (0DnAAwud94Oq1HgCMvnHALBm, 80TvKZRCBl7tGLeKGkMzu272, knLFg1IV_xRojCjP882Ryhbi, Pi73vh5o7wsNFbYsY02umoH4, sadCgPIJm9mfW54mcPIrJ1Cd)); caused by
2022-05-15 08:19:46 UTC -- error   -- App\Actions\Album\Delete::do -- 115 -- SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`lychee`.`albums`, CONSTRAINT `albums_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `albums` (`id`)) (SQL: delete from `albums` where `id` in (0DnAAwud94Oq1HgCMvnHALBm, 80TvKZRCBl7tGLeKGkMzu272, knLFg1IV_xRojCjP882Ryhbi, Pi73vh5o7wsNFbYsY02umoH4, sadCgPIJm9mfW54mcPIrJ1Cd)); caused by
2022-05-15 08:07:28 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 --
```

### Output of the diagnostics  [REQUIRED]

```
-----------
Warning: 'D:\phpEnv\www\Lychee\public\dist\user.css' does not exist or has insufficient read/write privileges.
Warning: Dropbox import not working. dropbox_key is empty.
Warning: zend.assertions is enabled although Lychee is not in debug mode. Outside of debugging, code generation for assertions is recommended to be disabled for efficiency reasons

System Information
------------------
Lychee Version (release):        4.5.1
DB Version:                      4.5.1

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          WINNT
PHP Version:                     8.1
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        Asia/Shanghai
Max uploaded file size:          200M
Max post size:                   256M
Max execution time:              0
MySQL Version:                   5.7.28

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1808
GD Version:                      bundled (2.1.0 compatible)

Config Information
------------------
version:                         040501
check_for_updates:               0
sorting_photos_col:              taken_at
sorting_photos_order:            ASC
sorting_albums_col:              max_taken_at
sorting_albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1
new_photos_notification:         0
legacy_id_redirection:           1
```

### Browser and system
windows10  Chrome

**Comment by nagmat84** [comment] 2022-05-15 09:42
Sorry, I just had to edit your issue and fix the formatting to make it more readable.

**Comment by sunosv** [comment] 2022-05-15 09:48
> Sorry, I just had to edit your issue and fix the formatting to make it more readable.

Sorry about that👀

**Comment by nagmat84** [comment] 2022-05-15 10:04
Thank your for your bug report and the great analysis. This should really help to reproduce the problem. I appreciate your illustration your illustration of the folder hierarchy and the screenshots of your table `albums`. They help a lot to understand the problem.

I haven't tried it yet, but I am convinced that the bug is there, because it is very, very plausible. The 3rd-party code for the nested set model is a very fragile (and IMHO crappy) library.

Before my big re-factoring, the previous Lychee code basically invoked `::fixTree` after every tree operation. `::fixTree` simply overwrites all the previous `_lft` and `_rgt` values and re-enumerates the entire tree in a depth-first search. The method just re-creates the entire tree (as if you would initialize the nested set model for the first time) and collects some statistics about how many `_lft`, `_rgt` values have been wrong. But obviously, it defeats the whole purpose of an _efficient_ nested set model, if one re-creates the entire structure for every operation via a full re-enumeration. This was a cheap work-around to be "on the safe side".

As part of my re-factoring I removed most of the (unconditional) calls to `::fixTree` and I fixed some of the bugs in the nested set library. But chances are high that there are still plenty. You cannot imagine how much I desire to take care of that. :weary: In particular, I fear that I fix one error in the library and just break something else. (But that shouldn't be your problem.)

However, one aspect strikes me as surprising. You wrote that you ran the console command `./artisan lychee:fix-tree` without success. Just to be sure that we are on the same page here. Your DB was in the inconsistent state as shown in the 2nd screenshot (i.e. with the dublicate `_lft`, `_rgt` values `4` and `5` for the 2nd and 3rd album), you ran `./artisan lychee:fix-tree` and it had no effect, but the values were still broken? That would be disturbing. Because `./artisan lychee:fix-tree` simply calls `::fixTree` of the library.

My first thought as some kind of emergency quick fix would have been to re-insert calls to `::fixTree` in the Lychee code after every album operation again at the costs of efficiency until I will have had the time to fix the true problem. But you are telling me that this won't work.

**Comment by nagmat84** [comment] 2022-05-15 10:12
BTW: I feared problems like that and I would have liked to introduce deferred uniqueness and check constraints on the DB level for the `_lft` and `_rgt` values to enforce the consistency of the nested set model on the DB level, too. This would not solve this problem, but ensure that your data is safe. Unfortunately, this only supported by PostgreSQL, neither MySQL nor SQLite.

**Comment by sunosv** [comment] 2022-05-15 12:00
> My first thought as some kind of emergency quick fix would have been to re-insert calls to `::fixTree` in the Lychee code after every album operation again at the costs of efficiency until I will have had the time to fix the true problem. But you are telling me that this won't work.

I mean it's not completely useless, and when I delete it, _rgt or _lft messes up. Then use fixtree, it fixes the conflict, but I still get delete errors. Until all folders are deleted, you need to use fixtree every time

**Comment by sunosv** [comment] 2022-05-15 12:03
> I haven't tried it yet, but I am convinced that the bug is there, because it is very, very plausible. The 3rd-party code for the nested set model is a very fragile (and IMHO crappy) library.
> 
> [...]
> 
> As part of my re-factoring I removed most of the (unconditional) calls to `::fixTree` and I fixed some of the bugs in the nested set library. But chances are high that there are still plenty. You cannot imagine how much I desire to take care of that. 😩 In particular, I fear that I fix one error in the library and just break something else. (But that shouldn't be your problem.)

I can imagine how maddening it would be 😢

**Comment by sunosv** [comment] 2022-05-15 12:42
> BTW: I feared problems like that and I would have liked to introduce deferred uniqueness and check constraints on the DB level for the `_lft` and `_rgt` values to enforce the consistency of the nested set model on the DB level, too. This would not solve this problem, but ensure that your data is safe. Unfortunately, this only supported by PostgreSQL, neither MySQL nor SQLite.

I think it will spend a lot of your time to fix the true problem.and It    will work that the idea you have mentioned. lets do it

**Comment by nagmat84** [comment] 2022-05-15 16:04
> I mean it's not completely useless, and when I delete it, _rgt or _lft messes up. Then use fixtree, it fixes the conflict, but I still get delete errors. Until all folders are deleted, you need to use fixtree every time

Ah, ok. Hence as a hot patch we could simply call `fixTree` every time after a tree operation. That you have to do it for every manual delete operation is somehow expected, but you would not need to do it manually anymore when we do it in the code.

I feared that `fixTree` would not do anything.

**Comment by sunosv** [comment] 2022-05-15 16:41
> > I mean it's not completely useless, and when I delete it, _rgt or _lft messes up. Then use fixtree, it fixes the conflict, but I still get delete errors. Until all folders are deleted, you need to use fixtree every time
> 
> Ah, ok. Hence as a hot patch we could simply call `fixTree` every time after a tree operation. That you have to do it for every manual delete operation is somehow expected, but you would not need to do it manually anymore when we do it in the code.
> 
> I feared that `fixTree` would not do anything.

let's try,but what can I do?I want test it as soon as possible

**Comment by sunosv** [comment] 2022-05-17 07:37
Still no progress on this issue?😮‍💨  @nagmat84

**Comment by nagmat84** [comment] 2022-05-17 16:39
First of all, Lychee is free-time project of 4-5 maintainers which are committed to the well-being of the project, but still have a professional full-time job which is not Lychee and also have a social life. I have already replied to this problem in less then a few hours after the initial post. Moreover, I already confirmed that it is a bug. However, I won't get to work on this issue before next weekend.

I understand that this is an annoying and somewhat severe bug, because it messes with the album structure.

But as a workaround you can still delete sub-trees of albums individually. The bug only occurs if you do not delete a single subtree (with a single parent), but a set of sub-trees, i.e. a so-called "forest". The library for the nested set model is not prepared for that. Even though the library offers a method `->delete(array $ids)` it only considers a single subtree when it comes to the re-calculation of the indexes. (You could call this a bug in the library, because its API promises more than it supports).

I will have look into that but you need a little bit of patience.

**Comment by sunosv** [comment] 2022-05-17 16:47
> First of all, Lychee is free-time project of 4-5 maintainers which are committed to the well-being of the project, but still have a professional full-time job which is not Lychee and also have a social life. I have already replied to this problem in less then a few hours after the initial post. Moreover, I already confirmed that it is a bug. However, I won't get to work on this issue before next weekend.
> 
> I understand that this is an annoying and somewhat severe bug, because it messes with the album structure.
> 
> But as a workaround you can still delete sub-trees of albums individually. The bug only occurs if you do not delete a single subtree (with a single parent), but a set of sub-trees, i.e. a so-called "forest". The library for the nested set model is not prepared for that. Even though the library offers a method `->delete(array $ids)` it only considers a single subtree when it comes to the re-calculation of the indexes. (You could call this a bug in the library, because its API promises more than it supports).
> 
> I will have look into that but you need a little bit of patience.


Sorry， maybe I'm in too much of a hurry on this issue. But I should have understood more about the precious time you put into keeping this project going. Thank you for your patient reply, and I will be patiently waiting for next weekend as well. Thank you！

**Comment by nagmat84** [comment] 2022-05-22 12:33
I assume the bug should be fixed by the linked PR. @sunosv: Can you confirm that the PR fixes the bug?

**Comment by sunosv** [comment] 2022-05-24 19:11
> I assume the bug should be fixed by the linked PR. @sunosv: Can you confirm that the PR fixes the bug?

Great job! It's working, Thank you!

**Closed as completed** 2022-05-24 20:14 UTC
