### ISSUE TITLE
ShareX uploading + retrieving the original URL

### ISSUE THREAD

**Issue by iisworm** [LycheeOrg/Lychee#1092] opened 2021-08-29 15:55 UTC
Title. I use ShareX to upload screenshots so I can easily share them via URL. I had previously used ZenPhoto for this but wanted something that looked better, and made looking for images easier. But I've learned that this randomly generates names for files, which means I cannot return the URL (or at least I don't know how, I'm a beginner with PHP/whatever. Is it possible to only use the given filenames as a path? Instead of generating a huge unnecessary name (in my case)?

Edit: I found the API. So far anything I do in Postman, returns a 
"Oops! An Error Occurred 
The server returned a "405 Method Not Allowed"."

And have no idea what I'm supposed to be doing.

**Comment by LouisVallat** [comment] 2021-11-08 08:59
Hi,
Regarding the API, are you sure that you are sending the JSON-formatted data using a `POST` request? I can reproduce a `405: Method not allowed` when sending the correct data with a `GET` request.

**Comment by nagmat84** [comment] 2022-03-27 11:02
OP did not respond within 5 months. The problem is still unclear. Closing this issue.

**Closed as completed by nagmat84** 2022-03-27 11:02 UTC
Labels: More info required
