### ISSUE TITLE
[regression] Error 500 on albums::get() when album are shared between users (when logging on said user).

### ISSUE THREAD

**Issue by astrofrog** [LycheeOrg/Lychee#643] opened 2020-06-28 22:36 UTC
### Detailed description of the problem

If I make an album as the primary user everything works fine, but if I create a secondary user and give it access to the album, then when I try logging in as that account, I see a 'Server error or API not found' red banner and errors in the console:

```
/api/Albums::get:1 Failed to load resource: the server responded with a status of 500 ()
main.js?1593291479:4039

Objectdescription: "Server error or API not found."params: function: "Albums::get"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()response: ""__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
lychee.error @ main.js?1593291479:4039
```

However, I can't figure out what the error might be - I tried seeing what the nginx and php logs contained in ``/var/log`` but couldn't see any more information.

### Steps to reproduce the issue

**Steps to reproduce the behavior:**

1. Create an album as primary user
2. Create a new user
3. Give access to the album to the new user
4. Log in as new user

A black screen appears and there is an error in the console (given above)

I'm using the ``dev`` tag of the docker container for lychee.

### Output of the diagnostics 

```
    Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.3
    Max uploaded file size:     20M
    Max post size:              100M
    SQLite Version:             3.27.2
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

    Config Information
    ------------------
    version:                    040006
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              0
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              Thomas Robitaille
    landing_title:              Photos
    landing_subtitle:           
    landing_facebook:           https://www.facebook.com/astrofrog
    landing_flickr:             https://www.flickr.com/thomasrobitaille
    landing_twitter:            https://www.twitter.com/astrofrog
    landing_instagram:          
    landing_youtube:            
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      1
    site_copyright_begin:       2020
    site_copyright_end:         2020
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               1
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0
    editor_enabled:             1
```

### Browser and system

Any browser, MacOS X 10.15.6

**Comment by ildyria** [comment] 2020-06-29 08:00
Will be fixed with #640

**Comment by pchampio** [comment] 2020-06-30 11:28
I still encounter this issue when the user hasn't the 'Allow upload' right.
![image](https://user-images.githubusercontent.com/7476655/86120858-55e39500-bad5-11ea-8e4c-9dd8efee3aca.png)
push user works, share users doesn't.

```


    Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.




    System Information
    --------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    local
    APP_DEBUG:                  true
    
    System:                     Linux
    PHP Version:                7.3
    Max uploaded file size:     10G
    Max post size:              10G
    PostgreSQL Version:         PostgreSQL 10.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5




    Config Information
    --------------
    sorting_Photos_order:       ASC
    site_copyright_enable:      0
    check_for_updates:          0
    SL_enable:                  0
    SL_for_admin:               0
    imagick:                    1
    skip_duplicates:            0
    lang:                       en
    layout:                     1
    image_overlay:              1
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    version:                    040006
    compression_quality:        90
    sorting_Photos_col:         takestamp
    landing_background:         dist/cat.jpg
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    site_copyright_begin:       2019
    site_copyright_end:         2019
    additional_footer_text:     
    display_social_in_gallery:  0
    public_recent:              0
    Mod_Frame_refresh:          30
    public_search:              1
    image_overlay_type:         exif
    default_license:            CC-BY-NC-SA
    landing_page_enable:        0
    landing_owner:              Pierre C
    landing_title:              Pierre C
    landing_subtitle:           
    landing_facebook:           
    landing_flickr:             
    landing_twitter:            
    landing_instagram:          
    landing_youtube:            
    site_title:                 Albums de Pierre
    sorting_Albums_col:         min_takestamp
    sorting_Albums_order:       DESC
    public_starred:             0
    downloadable:               0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    share_button_visible:       0
    update_check_every_days:    3
    has_exiftool:               1
    import_via_symlink:         0
    has_ffmpeg:                 1
    map_display:                0
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0
    editor_enabled:             1
    photos_wraparound:          0
    recent_age:                 4
```

```
lychee_laravel           | Lychee Version: 4.0.6 (dev)
lychee_laravel           | Lychee Commit:  f5ebb14
lychee_laravel           | https://github.com/LycheeOrg/Lychee/commit/f5ebb14de86caa5890e503efab83f62952d73116
```

```
{
    "message": "Object of class stdClass could not be converted to string",
    "exception": "ErrorException",
    "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Support/Str.php",
    "line": 449,
    "trace": [
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Support/Str.php",
            "line": 449,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/QueryException.php",
            "line": 57,
            "function": "replaceArray",
            "class": "Illuminate\\Support\\Str",
            "type": "::"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/QueryException.php",
            "line": 40,
            "function": "formatMessage",
            "class": "Illuminate\\Database\\QueryException",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 672,
            "function": "__construct",
            "class": "Illuminate\\Database\\QueryException",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 631,
            "function": "runQueryCallback",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 339,
            "function": "run",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 2202,
            "function": "select",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 2190,
            "function": "runSelect",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 2685,
            "function": "Illuminate\\Database\\Query\\{closure}",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 2191,
            "function": "onceWithColumns",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
            "line": 539,
            "function": "get",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
            "line": 523,
            "function": "getModels",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/ModelFunctions/AlbumFunctions.php",
            "line": 315,
            "function": "get",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/ModelFunctions/AlbumsFunctions.php",
            "line": 229,
            "function": "customSort",
            "class": "App\\ModelFunctions\\AlbumFunctions",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/Http/Controllers/AlbumsController.php",
            "line": 64,
            "function": "getToplevelAlbums",
            "class": "App\\ModelFunctions\\AlbumsFunctions",
            "type": "->"
        },
        {
            "function": "get",
            "class": "App\\Http\\Controllers\\AlbumsController",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 239,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 196,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 685,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 76,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/app/Http/Middleware/VerifyCsrfToken.php",
            "line": 60,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "App\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php",
            "line": 39,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\AuthenticateSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 116,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 62,
            "function": "handleStatefulRequest",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",
            "line": 66,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 687,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 662,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 628,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 617,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 165,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/bepsvpt/secure-headers/src/SecureHeadersMiddleware.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Bepsvpt\\SecureHeaders\\SecureHeadersMiddleware",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/html/Lychee/public/index.php",
            "line": 74,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}
```

**Comment by ildyria** [comment] 2020-06-30 12:04
I could not reproduce. Weird.

**Comment by pchampio** [comment] 2020-06-30 13:34
It's not because of the users right, I'm wrong.

**Comment by pchampio** [comment] 2020-06-30 13:51
the same steps:

Steps to reproduce the behavior:

    Create an album as primary user
    Create a new user
    Give access to the album to the new user
    Log in as new user

on https://github.com/LycheeOrg/Lychee/commit/f5ebb14de86caa5890e503efab83f62952d73116 doesn't fixes my issue.

**Comment by ildyria** [comment] 2020-06-30 15:44
will check.

**Comment by ildyria** [comment] 2020-07-01 09:46
I have a paper deadline on July 5th, ([for the curious](https://cans2020.at/)). I will take a look at it then.
From what I understood, this is only breaking when there is album sharing between users.

Problem is either on those two:
https://github.com/LycheeOrg/Lychee/blob/master/app/ModelFunctions/AlbumsFunctions.php
https://github.com/LycheeOrg/Lychee/blob/master/app/ModelFunctions/AlbumFunctions.php

**Comment by ildyria** [comment] 2020-07-06 14:04
Fixed in the last PR. :+1:

**Closed as completed** 2020-07-06 14:39 UTC
