### ISSUE TITLE
[Enhancement] Add lazy loading of images

### ISSUE THREAD

**Issue by warpdesign** [LycheeOrg/Lychee#793] opened 2020-11-18 15:31 UTC
I have created an album with 2000 photos and viewing this album literally kills the browser: it crawls.

Suggestion: add lazy loading and only load/display visible images on the page.

**Comment by kamil4** [comment] 2020-11-18 15:35
Actually, the images are already loaded lazily. However, the layout is static, and we believe that that's what the browsers are having problems with.

I'm closing this as it's effectively a duplicate of #251.

**Closed as completed by kamil4** 2020-11-18 15:35 UTC
Labels: duplicate
