### ISSUE TITLE
LazyLoadingViolationException on /api/Albums::get

### ISSUE THREAD

**Issue by AnnoyingTechnology** [LycheeOrg/Lychee#1608] opened 2022-11-27 16:47 UTC
### Detailed description of the problem [REQUIRED]

An XHR request provokes a 500 Error with the following reponse
```json
{
    "message": "Server Error",
    "exception": "LazyLoadingViolationException"
}
```

But the Exception is caught somewhere so nothing gets logged to `laravel.log`, which doesn't me to debug further.

### Steps to reproduce the issue

1. Install Lychee with php 8.1
2. Open it

### Output of the diagnostics  [REQUIRED]

```
Diagnostics
-----------
Warning: /var/www/domains/REDACTED/public/uploads/ is owned by group www-data, but should be owned by one out of root
Warning: /var/www/domains/REDACTED/public/uploads/thumb2x is owned by group www-data, but should be owned by one out of root
Warning: /var/www/domains/REDACTED/public/uploads/small2x is owned by group www-data, but should be owned by one out of root
Warning: /var/www/domains/REDACTED/public/uploads/medium is owned by group www-data, but should be owned by one out of root
Warning: /var/www/domains/REDACTED/public/uploads/original is owned by group www-data, but should be owned by one out of root
Warning: 7 more directories with wrong owner
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone

System Information
------------------
Lychee Version (git):                    master (1aa57e0) -- Up to date (1 minutes ago).
DB Version:                              4.6.2

composer install:                        --no-dev
APP_ENV:                                 production
APP_DEBUG:                               false

System:                                  Linux
PHP Version:                             8.1.13
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                UTC
Max uploaded file size:                  2M
Max post size:                           8M
Max execution time:                      0
SQLite Version:                          3.34.1

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1691
GD Version:                              2.3.3

Config Information
------------------
version:                                 040602
check_for_updates:                       0
sorting_photos_col:                      taken_at
sorting_photos_order:                    ASC
sorting_albums_col:                      max_taken_at
sorting_albums_order:                    ASC
imagick:                                 1
skip_duplicates:                         0
small_max_width:                         0
small_max_height:                        360
medium_max_width:                        1920
medium_max_height:                       1080
lang:                                    en
layout:                                  1
image_overlay_type:                      desc
default_license:                         reserved
compression_quality:                     90
full_photo:                              1
delete_imported:                         0
mod_frame_enabled:                       1
mod_frame_refresh:                       30
thumb_2x:                                1
small_2x:                                1
medium_2x:                               1
landing_page_enable:                     0
site_owner:                              REDACTED
landing_title:                           REDACTED
landing_subtitle:                        REDACTED
sm_facebook_url:                         https://www.facebook.com/REDACTED
sm_flickr_url:                           
sm_twitter_url:                          https://www.twitter.com/REDACTED
sm_instagram_url:                        
sm_youtube_url:                          https://www.youtube.com/REDACTED
landing_background:                      dist/cat.jpg
site_title:                              REDACTED
footer_show_copyright:                   1
site_copyright_begin:                    2001
site_copyright_end:                      2025
footer_additional_text:                  
footer_show_social_media:                0
public_search:                           0
SL_enable:                               0
SL_for_admin:                            0
public_recent:                           0
recent_age:                              1
public_starred:                          0
downloadable:                            0
photos_wraparound:                       1
map_display:                             0
zip64:                                   1
map_display_public:                      0
map_provider:                            Wikimedia
force_32bit_ids:                         0
map_include_subalbums:                   0
update_check_every_days:                 3
has_exiftool:                            0
share_button_visible:                    0
import_via_symlink:                      0
has_ffmpeg:                              0
location_decoding:                       0
location_decoding_timeout:               30
location_show:                           1
location_show_public:                    0
rss_enable:                              0
rss_recent_days:                         7
rss_max_items:                           100
prefer_available_xmp_metadata:           0
editor_enabled:                          1
lossless_optimization:                   0
swipe_tolerance_x:                       150
swipe_tolerance_y:                       250
local_takestamp_video_formats:           .avi|.mov
log_max_num_line:                        1000
unlock_password_photos_with_url_param:   0
nsfw_visible:                            1
nsfw_blur:                               0
nsfw_warning:                            0
nsfw_warning_admin:                      0
nsfw_banner_override:                    
map_display_direction:                   1
album_subtitle_type:                     oldstyle
upload_processing_limit:                 4
public_photos_hidden:                    1
new_photos_notification:                 0
legacy_id_redirection:                   1
zip_deflate_level:                       6

```

### Browser and system

PHP 8.1
Chromium & Curl 
Debian both client & server

**Comment by AnnoyingTechnology** [comment] 2022-11-27 16:56
I managed to get a trace 
```json
{
    "message": "Attempted to lazy load [size_variants] on model [App\\Models\\Photo] but lazy loading is disabled.",
    "exception": "Illuminate\\Database\\LazyLoadingViolationException",
    "file": "/var/www/domains/REDACTED/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php",
    "line": 563,
    "trace": [
        {
            "file": "/var/www/domains/REDACTED/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php",
            "line": 522,
            "function": "handleLazyLoadingViolation",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/var/www/domains/REDACTED/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php",
            "line": 453,
            "function": "getRelationValue",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/var/www/domains/REDACTED/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
            "line": 2218,
            "function": "getAttribute",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/var/www/domains/REDACTED/app/Models/Extensions/Thumb.php",
            "line": 83,
            "function": "__get",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/var/www/domains/REDACTED/app/Relations/HasAlbumThumb.php",
            "line": 276,
            "function": "createFromPhoto",
            "class": "App\\Models\\Extensions\\Thumb",
            "type": "::"
        },
       // [...] shortened for clarity
        {
            "file": "/var/www/domains/REDACTED/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 134,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/domains/REDACTED/public/index.php",
            "line": 74,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ],
    "previous_exception": null
}
```

**Comment by AnnoyingTechnology** [comment] 2022-11-27 17:04
I fixed it by commenting out `Model::shouldBeStrict();`  from `app/Providers/AppServiceProvider.php`. 

And added back 
```php
Model::preventAccessingMissingAttributes();
Model::preventSilentlyDiscardingAttributes();
```

to preserve some "strict"ness.

**Comment by gdureuil** [comment] 2022-11-27 18:09
I updated from commit 41ce095 to 1aa57e0 (latest at that time) and had the same error. Lychee had only "Internal Server Error" on the main page. Saw the same error on LazyLoadingViolationException in browser console.

The fix from AnnoyingTechnology worked and lychee is now working again, but this should be fixed in the future.

EDIT :
Excerpt from Lychee log:
`2022-11-27 18:01:54 UTC -- error   -- Illuminate\Database\Eloquent\Model::handleLazyLoadingViolation -- 563 -- Attempted to lazy load [size_variants] on model [App\Models\Photo] but lazy loading is disabled.
2022-11-27 18:01:54 UTC -- error   -- App\Models\Extensions\Thumb::createFromPhoto -- 83 -- Attempted to lazy load [size_variants] on model [App\Models\Photo] but lazy loading is disabled.; caused by`

**Comment by ildyria** [comment] 2022-11-27 22:50
Adding the following in the app/Models/Photo.php also fixes it:
```php
	/**
	 * @var array<int,string> By default preload all the size_variants
	 */
	protected $with = [
		'size_variants',
	];
```

**Closed as completed** 2022-11-28 07:49 UTC
Labels: High Priority
